# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'OLXTest' do

pod 'TPKeyboardAvoiding'
pod 'MBProgressHUD'
pod "AFNetworking", "~> 2.0"

end

target 'OLXTestTests' do

end

